### PR TITLE
update links for FORD

### PR DESCRIPTION
**Pull request by jvdp1**
Here are correct links for FORD.

### CODE REVIEW

**Comment by ghbrown** [comment]
Thanks for the help. My only comment is that I believe Sebastian wanted the links to lack the description, for example `...#eye` rather than `...#eye-construct-the-identity-matrix`, but we could just bring this up on the main PR if needed?

**Comment by jvdp1** [comment]
the link `...#eye` points to nothing, and so is redirected `to ...stdlib_linalg.html`.

**Comment by ghbrown** [comment]
Hmm, how did he intent to keep the descriptions out of the links then? Anyway, I'll merge.

**Comment by jvdp1** [comment]
Well, I don't know. However, we did it like I proposed in other modules
(see e.g., `stdlib_stats`, or `stdlib_sorting`)

Le lun. 4 oct. 2021 à 21:05, Gabriel Brown ***@***.***> a
écrit :

**Pull request merged**
